export const CHANGE_CURRENT_SONG = 'play/CHANGE_CURRENT_SONG'
export const CHANGE_PLAY_LIST = 'play/CHANGE_PLAY_LIST'
export const CHANGE_CURRENT_SONG_INDEX = 'play/CHANGE_CURRENT_SONG_INDEX'

export const CHANGE_SEQUENCE = 'play/CHANGE_SEQUENCE'

export const CHANGE_LYRIC_LIST = 'play/CHANGE_LYRIC_LIST'
export const CHANGE_CURRENT_LYRIC_INDEX = 'play/CHANGE_CURRENT_LYRIC_INDEX'